### ISSUE TITLE
When there are no past sessions, two "toggle past" buttons appear and look wonky.

### ISSUE THREAD

**Issue by sidstamm** [KixorTech/CourseUp#2]
It is still a little funky with no past sessions:
> ![image](https://user-images.githubusercontent.com/613269/70063158-4f2f8680-15b5-11ea-96d0-99477f1f9945.png)

Might be good to dedupe when no sessions are in the past.

**Comment by sidstamm** [comment]
Relevant conversations on commit https://github.com/kixortech/CourseUp/commit/5ed36bded27d8863979da510b1da43479bd121ff

**Comment by KixorTech** [comment]
This should be fixed in 3308c67fd992f571d20fca7a4ef900f3080ac1dd

**Comment by KixorTech** [comment]
That fix stopped the toggle button from working correctly. Should work again in 3a34cb0a8c6b2d5c7752243d31b169e81ccd3e2c
